@accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG0iLCJpYXQiOjE3MzQxMDk0NzYsImV4cCI6MTczNDExMjQ3Niwib3duZXIiOiIiLCJyb2xlcyI6WyJ1c2VyOnJlYWQiLCJ1c2VyOndyaXRlIiwiYWRtaW46cmVhZCIsImd1ZXN0IiwiYWRtaW46d3JpdGUiXX0.i5gNu4vazLFjVw-_jchXstqNr5nqBVytUbFmmTZbZ6AdPPcsloNWmZc6MopfK-QpFDIuu80OXTzg5-S50ehE2g

POST http://localhost:8080/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "adm",
    "password" : "P@ssw0rd"
}


###
GET http://localhost:8080/api/v1/admins/roles/list HTTP/1.1
Authorization: Bearer {{accessToken}}

###
GET http://localhost:8080/api/v1/admins/roles/list?filter=user HTTP/1.1
Authorization: Bearer {{accessToken}}

###
GET http://localhost:8080/api/v1/admins/roles?filter=user HTTP/1.1
Authorization: Bearer {{accessToken}}

###
POST http://localhost:8080/api/v1/admins/roles HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "roleName": "RO",
    "permissions": [
        "USER_READ",
        "USER_WRITE"
      ]
}

###
PUT http://localhost:8080/api/v1/admins/roles HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id": 3,
    "roleName": "ROLE",
    "permissions": [
        "USER_READ",
        "USER_WRITE"
      ]
}

###
GET http://localhost:8080/api/v1/admins/roles/3 HTTP/1.1
Authorization: Bearer {{accessToken}}


###
DELETE http://localhost:8080/api/v1/admins/roles/3 HTTP/1.1
Authorization: Bearer {{accessToken}}

###
PATCH  http://localhost:8080/api/v1/admins/roles/3/active HTTP/1.1
Authorization: Bearer {{accessToken}}
